server:
  port: 8882
  servlet:
    context-path: /mgt
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

logging:
  file: logs/pc-core.log 
  level:
    root: info

pc.core.base.url: http://localhost:8881
pc.core.context-path: /core

auth.core.base.url: http://localhost:8883
auth.core.context-path: /auth

COOKIE_AUTH_KEY: SOFT_USER_COOKIE